version: '3.7'

services:
  flask:
    build:
      context: Flask/.
    image: 644435390668.dkr.ecr.eu-west-3.amazonaws.com/pp_flask_app:latest
    container_name: flask
    environment:
      MONGODB_URI: mongodb://mongodb:27017/
    ports:
    - 5000:5000
    networks:
      - public
      - private
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - private
  nginx:
    build:
      context: Nginx/.
    image: 644435390668.dkr.ecr.eu-west-3.amazonaws.com/pp_nginx:latest
    container_name: nginx
    ports:
    - 5001:80
    environment:
      BACKEND: flask
    command: /bin/sh -c "export BACKEND && envsubst '$${BACKEND}' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
    networks:
      - public
    depends_on:
      - flask
networks:
  public:
  private:
